### PR TITLE
fix for Centos 7

### PR DESCRIPTION
**Pull request by mortbauer**
I have seen #9 but from my testing I only managed to make it work if I completely remove that line.

### CODE REVIEW

**Comment by dmpe** [comment]
@yuvipanda

**Comment by hansen-m** [comment]
I can confirm this is still an issue with 219.

**Comment by yuvipanda** [comment]
Thanks for the PR, @mortbauer. Instead of commenting out the line, if you just remove it I'm happy to merge it.

**Comment by yuvipanda** [comment]
Thanks, @mortbauer!

**Comment by subgero** [comment]
@mortbauer  Could you please tell us, What line are you talking about?

**Comment by mortbauer** [comment]
@subgero please just have a look at the pull request, it removes one line

**Comment by adamboutcher** [comment]
Can confirm removing this line fixed spwaning for me on CentOS 7.8

**Comment by yuvipanda** [comment]
I released 0.14 with this fix a week ago.

**Comment by adamboutcher** [comment]
Well it hasn't hit upstream into tljh yet then because I had to edit that line yesterday.

**Comment by yuvipanda** [comment]
@adamboutcher I've bumped it in https://github.com/jupyterhub/the-littlest-jupyterhub/pull/602.

Does TLJH run on Centos? I thought we bailed early if it isn't ubuntu...

**Comment by adamboutcher** [comment]
It does bail but its only an issue because they hard code apt, removing any apt lines, manually installing the deps and removing the Ubuntu check and it magically works.

**Pull request merged**
